### ISSUE TITLE
Google Analytics - Send visitors traffic graph and trends prediction to Slack channel

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1025]
**Describe the solution you'd like**
Get traffic from website analysis from Google Analytics, use algorithm to predict trends, send graph and message to Slack.

- Input
Setup Google Analytics
Setup Slack

- Model
TBD

- Output
Generate traffic graph
Generate message
Send to Slack page

**Comment by Gaurav1401** [comment]
@jravenel Sir, for this I guess we also need raw data. As google analytics directly shows the visualizations of the website.
Please correct me if I am wrong..

I think I can handle this issue, if little guidance is provided..

**Comment by Dr0p42** [comment]
Hello @Gaurav1401, there is already a pull request for this issue: https://github.com/jupyter-naas/awesome-notebooks/pull/1029

You can review it if you want to contribute, otherwise you could read [this part](https://www.notion.so/naas-official/Code-contributor-journey-164779502e2a4ca5950d63eea7a2d39f#7572fbeae0d64af8b77bae853a2eec54) on "How to chose a task" it will help you get started 👍 

You should focus on issues that are in "Backlog" for now, so here --> https://github.com/orgs/jupyter-naas/projects/4#column-14468320
