### ISSUE TITLE
LinkedIn Sales Navigator - Extract Leads List from URL: 403 client error

### ISSUE THREAD

**Issue by quangtho2910** [jupyter-naas/awesome-notebooks#1692]
**Describe the bug**
Got an error when trying to extract leads from this URL: [https://www.linkedin.com/sales/search/people?savedSearchId=50452421&sessionId=kSLaK3YWTYq0IKM2MgctOw%3D%3D](url)

See error:
`HTTPError: 403 Client Error: Forbidden for url: https://3hz1hdpnlf.execute-api.eu-west-1.amazonaws.com/prod/leads/getList?url=https%3A%2F%2Fwww.linkedin.com%2Fsales%2Fsearch%2Fpeople%3FsavedSearchId%3D50452421%26sessionId%3DkSLaK3YWTYq0IKM2MgctOw%253D%253D&start=0&count=100`

**Screenshots**
![image](https://user-images.githubusercontent.com/3017528/233546032-6dad3e62-f031-4652-ba5e-624f7c61545b.png)

**Comment by FlorentLvr** [comment]
@quangtho2910! Thank you for contacting us! We appreciate your outreach. We will investigate the reported bug and aim to provide a resolution in the next weeks. 
Since there is no official API available for LinkedIn Sales Navigator, we are responsible for developing and maintaining our own solution, which requires dedicated resources. Currently, I am the only person working on this project. 
To speed up the development process, we are seeking companies who may be interested in sponsoring this API.
Is this something that might be of interest to you?
@jravenel

**Comment by FlorentLvr** [comment]
> @quangtho2910! Thank you for contacting us! We appreciate your outreach. We will investigate the reported bug and aim to provide a resolution in the next weeks. Since there is no official API available for LinkedIn Sales Navigator, we are responsible for developing and maintaining our own solution, which requires dedicated resources. Currently, I am the only person working on this project. To speed up the development process, we are seeking companies who may be interested in sponsoring this API. Is this something that might be of interest to you? @jravenel @Dr0p42

**Comment by quangtho2910** [comment]
@FlorentLvr 
Thank you so much for your response. I'm just a developer too, can't be sponsoring this API with my capability... Maybe you can open source the private API project so I and other developers can develop and improve those API together?

**Comment by FlorentLvr** [comment]
This issue is being closed because it is not a priority and will not be addressed.
