### ISSUE TITLE
What is this repo about?

### ISSUE THREAD

**Issue by nyck33** [jupyter-naas/awesome-notebooks#1778]
I am not getting the point.  Also your social login on naas.ai were all broken.

**Comment by FlorentLvr** [comment]
> I am not getting the point. Also your social login on naas.ai were all broken.

Hi @nyck33,

Hope you will find answers [here](https://github.com/jupyter-naas/awesome-notebooks#what-is-the-objective-of-this-repository-?) about the purpose of this repo. Otherwise, please let me know if you have any doubts. 

About the social login, which one did you try? Could you please give us more information about this bug to reproduce it on our end? Thank you 🙏

**Comment by nyck33** [comment]
I tried all 3 social logins on Firefox, Windows 11 and would get the Firefox error page, from here: https://www.naas.ai/free-forever but they are working now.

**Comment by nyck33** [comment]
Yes it's all good.  Thanks!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
