### ISSUE TITLE
Github - Get list of profiles from teams

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#214]
The objective of this notebook is to get a dataframe of all the members of a Github organization. 

## Input: 
-  TEAM_URL = https://github.com/orgs/jupyter-naas/teams

## Model: 
Get data from Github API : https://docs.github.com/en/rest/reference/teams

Columns:
- GITHUB:  jupyter-naas
- TEAM: opensource-contributors
- TEAM_DESCRIPTION: Naas opensource contributors group
- NAME: 
- SLUG:  
- EMAIL: 
- WEBSITE:
- TWITTER:
- LOCATION: 
- ORGANIZATION:
- CREATED_AT:
- UPDATED_AT:

## Output: 
- show df

**Comment by jravenel** [comment]
Hello @Usamaliaquat123 Great talking to you today. I have invited you to Slack if you need further help. Otherwise feel free to write any question you may have here. 👍

**Comment by jravenel** [comment]
Hello @Usamaliaquat123, I'm bringing @SanjuEpic here, he will share his findings and help so that we can move the task forward. Good for you? Thanks

**Comment by SanjuEpic** [comment]
Hello @Usamaliaquat123  and @jravenel, i have completed the notebook template for this issue, which provides us the following information as given above in the output.

1. First we need to create a personal access token to get the details of our organization from here: https://github.com/settings/tokens
2. You will be asked to select scopes for the token. Which scopes you choose will determine what information and actions you 
will be able to perform against the API. 
3. You should be careful with the ones prefixed with write:, delete: and admin: as these might be quite destructive. 
4. You can find description of each scope in docs here (https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps).

Once this token is generated, then we are ready to go with the notebook i have completed.

These are the proposed columns, I would like to share:
['TEAM', 'SLUG', 'TEAM_DESCRIPTION', 'member_profile', 'GITHUB', 'NAME', 'EMAIL', 'LOCATION', 'ORGANIZATION', 'BIO', 'LOGIN_NAME', 'TWITTER', 'CREATED_AT', 'UPDATED_AT']

I have included login name column as well because for some users the name column had no value. 
Same goes for 'bio' column, if organization is none, sometimes are included in the bio column.
One new column named 'member_profile' is also included, which corresponds to the member's profile link.

Open to discussions corresponding to which columns are to be included finally.
