### ISSUE TITLE
Yahoo Finance - Commodities (Metals): COMEX Gold

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#572]
Using the same kind of template as https://github.com/jupyter-naas/awesome-notebooks/blob/master/YahooFinance/YahooFinance_Send_daily_prediction_to_Email.ipynb

and integrate the key parts of https://pycaret.gitbook.io/docs/learn-pycaret/official-blog/predicting-gold-prices-using-machine-learning for the prediction part.

**Comment by jravenel** [comment]
hey @bryan34500 the Issue is yours if you want to take it over.
Here is how to contribute: https://github.com/jupyter-naas/awesome-notebooks#how-to-contribute-
Here is a PR currently in review from @ayoub-berdeddouch where we are getting rid of the unnecessary legacy from the "Send daily prediction to Email template" to focus on the model → https://github.com/jupyter-naas/awesome-notebooks/issues/579

**Comment by jravenel** [comment]
`git fetch origin
git checkout 572-yahoo-finance-commodities-metals-comex-gold`

Branch created :)

**Comment by FlorentLvr** [comment]
Hi @bryan34500, hope you are doing well ? Do you need any help?

**Comment by jravenel** [comment]
@FlorentLvr @bryan34500 is out for the moment, for paternity. Got him a few weeks ago. 
We can assign it to other contributors.

**Comment by FlorentLvr** [comment]
Closing this issue due to naas awesome-notebooks reset strategy validated on 2023-05-25.
