### ISSUE TITLE
LinkedIn - Get company followers

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#72]
Input : 
- Your LinkedIn li_at session cookie

Model: 
Get data 

Output: 
fullName = Follower's fullname
firstName = Follower's firstname
lastName = Follower's lastname
profileUrl = LinkedIn profile URL of the follower
job = Follower's job
followedAt = Follower's following month
query = Company URL where the profile comes from
timestamp = Scraping date

https://phantombuster.com/automations/linkedin/6609751279582074/linkedin-company-follower-scraper

**Comment by Octonathan** [comment]
Hello, 

Problem with this template.

There is an error when I launch the automation. Do you know the cause of this error?
![Capture d’écran 2022-04-25 à 18 30 11](https://user-images.githubusercontent.com/103637511/165132914-7e9456c5-ea5f-4ff4-9abc-768b7a046c60.png)

Here are my settings : 
![Capture d’écran 2022-04-25 à 18 30 55](https://user-images.githubusercontent.com/103637511/165133019-9a105255-b48b-4081-9725-9ea9bbbe502c.png)

**Comment by FlorentLvr** [comment]
@Octonathan, TY for your feedback.
I think, this error is because you don't have the last version of naas.
Could you please check your version on your naas manager ?
![image](https://user-images.githubusercontent.com/48032461/165133685-80a8e108-e6f0-4bef-b575-159c80f2668b.png)

If you are not up to date, you can click on the yellow button to restart your engine. 

Let me know if it fixed your issue 🙏
