### ISSUE TITLE
Pipedrive - Get contact list

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#94]
Input : 
Pipedrive API Key

Output : 
Dataframe with contact list : FIRSTNAME, LASTNAME, JOB, COMPANY, PHONE, EMAIL

**Comment by calok64** [comment]
**_Sample data is used as follows. Field "JOB" is custom created and can be accessed by Field API Key._**
<img width="960" alt="sample_data"  #src="https://user-images.githubusercontent.com/36129343/136681690-0c8d44f6-887d-4a97-9945-29cd321fc26b.PNG">

**_Data is available via API as follows._**
<img width="937" alt="sample_output" src="https://user-images.githubusercontent.com/36129343/136681756-2f9841da-a710-4e68-abab-abebc29b0de6.png">

**Comment by FlorentLvr** [comment]
@calok64 , TY for contribution. I have made some changes to fit to our model:
- Change title to "# Pipedrive - Get Contact"
- Add naas
- Add tags
- Add markdown: ## Input, ##Model, ##Output"
=> Next time, could you please start from the "[template.ipynb](https://github.com/jupyter-naas/awesome-notebooks/blob/master/template.ipynb)" 
+ 
I can not run your because I have this error while importing library. 
Did you test this notebook on naas account ? Can you reproduce the issue ?
![image](https://user-images.githubusercontent.com/48032461/137698826-7818076b-ab6f-4111-b091-9aae98aa66d5.png)

**Comment by FlorentLvr** [comment]
@calok64 , I just added "!pip install pipedrive-python-lib" in the notebook and merge your contribution.
TY for your work.
![image](https://user-images.githubusercontent.com/48032461/141083829-ca4dfb74-b25c-4ea6-895c-fc3da1ea9aab.png)
