### ISSUE TITLE
 LinkedIn - Send likes to company posts

### ISSUE THREAD

**Issue by Valpiquard** [jupyter-naas/awesome-notebooks#976]
My goal is to like automatically new posts from a company page

**Comment by kaushalkrishna2000** [comment]
Should this continuously check if there is a new post form the company ?
Or Like 
Run Script -> Send Likes -> Script ends.  
 || Then repeat it once again ?

**Comment by jravenel** [comment]
Yes ! Exactly

**Comment by kaushalkrishna2000** [comment]
So the user has to manually run script everytime right ?

**Comment by FlorentLvr** [comment]
> So the user has to manually run script everytime right ?

@kaushalkrishna2000 ! Hope you are doing well!
You won't need to run script manually because we developed a scheduler feature on naas which allows you to run your notebook automatically based on a cron job. You can check the video here: https://www.google.com/search?q=scheduler+naas+youtube&rlz=1C1CHBF_esES1028FR1028&oq=scheduler+naas+youtube&aqs=chrome..69i57j33i10i160.3215j0j7&sourceid=chrome&ie=UTF-8#fpstate=ive&vld=cid:7a1ccf16,vid:ONiILHFItzs

So you just have to focus on the notebook.
Here is how i would do it regarding our IMO framework:
## Input:
### Setup Linkedin
LI_AT
JSESSIONID
Company URL

## Model
### Get company posts
-> you can find a template on GitHub

## Output
### Send Like
-> send like to post if not 

Is that more clear ?

Let me know if you have any questions!
